name: Commit Style

on:
  pull_request:

permissions: {}

jobs:
  check-commit-format:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check commit format
        uses: Homebrew/actions/check-commit-format@e99025eb970cfa124b8284a35463d87426917478 # 2026.09.28.1
        with:
          check_package_commit_format: false
